name: Mobile Trigger
description: 'Setting up core values and parameters for a mobile trigger for the pipeline.'

inputs:
  GOOGLE_SERVICE_ACCOUNT_JSON:
    description: 'The Google service account JSON file.'
    required: true
  RUBY_VERSION:
    description: 'The Ruby version to use.'
    required: true
  INSTALL_FASTLANE:
    description: 'Whether to install fastlane or not.'
    required: true
  PACKAGE_NAME_BASE:
    description: 'The package name of the mobile app.'
    required: true
  FLAVOR:
    description: 'The flavor of the mobile app.'
    required: true
  TRACK_TYPE:
    description: 'The track type to get the latest version code from (e.g., dev, stg, prd).'
    required: true
  WORKING_DIRECTORY:
    description: 'The working directory for the mobile project.'
    required: true
  ANDROID_KEYSTORE:
    description: 'The Android keystore file.'
    required: true
  ANDROID_KEYSTORE_PROPERTIES:
    description: 'The Android keystore properties file.'
    required: true
  NODE_VERSION:
    description: 'The Node version to use.'
    required: true
  INSTALL_NODE_MODULES:
    description: 'Whether to install node modules or not.'
    required: true
  INSTALL_BUNDLER:
    description: 'Whether to install bundler or not.'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set Environment Variables
      id: set-environment
      uses: marquesmateus93/piperoad/templates/set-environment@master

    - name: Decrypt Values
      uses: marquesmateus93/piperoad/templates/mobile-decrypt-values@master
      with:
        WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ inputs.GOOGLE_SERVICE_ACCOUNT_JSON }}

    - name: NodeJS Get Version Number
      uses: marquesmateus93/piperoad/templates/node-get-version-number@master

    - name: Setup Ruby and Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.RUBY_VERSION }}
        bundler-cache: true
    
    - name: Install Dependencies
      uses: marquesmateus93/piperoad/templates/mobile-install-dependencies@master
      with:
        INSTALL_FASTLANE: ${{ inputs.INSTALL_FASTLANE }}

    - name: Get Latest Version Code
      id: get_latest_version_code
      uses: marquesmateus93/piperoad/templates/mobile-get-latest-version-code@master
      with:
        PACKAGE_NAME_BASE: ${{ inputs.PACKAGE_NAME_BASE }}
        FLAVOR: ${{ inputs.FLAVOR }}
        TRACK_TYPE: ${{ inputs.TRACK_TYPE }}

    - name: Show Outputs
      shell: bash
      run: |
        echo "Environment: ${{ steps.set-environment.outputs.environment }}"
        echo "Version Number: ${{ steps.get_latest_version_code.outputs.version_code }}"
        echo "Next Version Code: ${{ steps.get_latest_version_code.outputs.next_version_code }}"

    - name: Deploy Android App
      uses: marquesmateus93/piperoad/actions/mobile-deploy-android@master
      with:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ inputs.GOOGLE_SERVICE_ACCOUNT_JSON }}
        RUBY_VERSION: ${{ inputs.RUBY_VERSION }}
        INSTALL_FASTLANE: ${{ inputs.INSTALL_FASTLANE }}
        PACKAGE_NAME_BASE: ${{ inputs.PACKAGE_NAME_BASE }}
        FLAVOR: ${{ inputs.FLAVOR }}
        TRACK_TYPE: ${{ inputs.TRACK_TYPE }}
        WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
        ANDROID_KEYSTORE: ${{ inputs.ANDROID_KEYSTORE }}
        ANDROID_KEYSTORE_PROPERTIES: ${{ inputs.ANDROID_KEYSTORE_PROPERTIES }}
        NODE_VERSION: ${{ inputs.NODE_VERSION }}
        VERSION_NUMBER: ${{ steps.get_latest_version_code.outputs.next_version_code }}
        VERSION_CODE: ${{ steps.get_latest_version_code.outputs.next_version_code }}